---
apiVersion: v1
kind: Namespace
metadata:
  name: flaskapp
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskapp-rc
  namespace: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: goraje/flaskapp:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---

